<?xml version="1.0" encoding="UTF-8" standalone="no"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsmp="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServicesProfile-Definitions-4.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:tyler:efm:wsdl:WebServicesProfile-Implementation-4.0"><import location="ecf-1.xsd" namespace="urn:oasis:names:tc:legalxml-courtfiling:wsdl:WebServicesProfile-Definitions-4.0"/><service name="FilingReviewMDEService">
		<port binding="wsmp:FilingReviewMDEPortSOAPBinding" name="FilingReviewMDEPort"><soap:address location="https://massachusetts.tylertech.cloud/efm/FilingReviewMDEPort.svc"/></port></service></definitions>