
package tyler.ecf.v5_0.extensions.tylercourtrecordmde;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.8
 * 2025-11-05T15:27:43.516-05:00
 * Generated source version: 4.0.8
 *
 */
public final class TylerCourtRecordMDE_TylerCourtRecordMDE_Client {

    private static final QName SERVICE_NAME = new QName("urn:tyler:ecf:v5.0:extensions:TylerCourtRecordMDE", "TylerCourtRecordMDEService");

    private TylerCourtRecordMDE_TylerCourtRecordMDE_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TylerCourtRecordMDEService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TylerCourtRecordMDEService ss = new TylerCourtRecordMDEService(wsdlURL, SERVICE_NAME);
        TylerCourtRecordMDE port = ss.getTylerCourtRecordMDE();

        {
        System.out.println("Invoking updateDocument...");
        tyler.ecf.v5_0.extensions.wrappers.UpdateDocumentRequestType _updateDocument_body = null;
        tyler.ecf.v5_0.extensions.wrappers.UpdateDocumentResponseType _updateDocument__return = port.updateDocument(_updateDocument_body);
        System.out.println("updateDocument.result=" + _updateDocument__return);


        }
        {
        System.out.println("Invoking recordService...");
        tyler.ecf.v5_0.extensions.wrappers.RecordServiceRequestType _recordService_body = null;
        tyler.ecf.v5_0.extensions.wrappers.RecordServiceResponseType _recordService__return = port.recordService(_recordService_body);
        System.out.println("recordService.result=" + _recordService__return);


        }
        {
        System.out.println("Invoking recordReceipt...");
        tyler.ecf.v5_0.extensions.wrappers.RecordReceiptRequestType _recordReceipt_body = null;
        tyler.ecf.v5_0.extensions.wrappers.RecordReceiptResponseType _recordReceipt__return = port.recordReceipt(_recordReceipt_body);
        System.out.println("recordReceipt.result=" + _recordReceipt__return);


        }
        {
        System.out.println("Invoking getParty...");
        tyler.ecf.v5_0.extensions.wrappers.GetPartyRequestType _getParty_body = null;
        tyler.ecf.v5_0.extensions.wrappers.GetPartyResponseType _getParty__return = port.getParty(_getParty_body);
        System.out.println("getParty.result=" + _getParty__return);


        }
        {
        System.out.println("Invoking getCaseHearings...");
        tyler.ecf.v5_0.extensions.wrappers.GetCaseHearingsRequestType _getCaseHearings_body = null;
        tyler.ecf.v5_0.extensions.wrappers.GetCaseHearingsResponseType _getCaseHearings__return = port.getCaseHearings(_getCaseHearings_body);
        System.out.println("getCaseHearings.result=" + _getCaseHearings__return);


        }
        {
        System.out.println("Invoking secureCase...");
        tyler.ecf.v5_0.extensions.wrappers.SecureCaseRequestType _secureCase_body = null;
        tyler.ecf.v5_0.extensions.wrappers.SecureCaseResponseType _secureCase__return = port.secureCase(_secureCase_body);
        System.out.println("secureCase.result=" + _secureCase__return);


        }
        {
        System.out.println("Invoking getServiceInformationHistory...");
        tyler.ecf.v5_0.extensions.wrappers.GetServiceInformationHistoryRequestType _getServiceInformationHistory_body = null;
        tyler.ecf.v5_0.extensions.wrappers.GetServiceInformationHistoryResponseType _getServiceInformationHistory__return = port.getServiceInformationHistory(_getServiceInformationHistory_body);
        System.out.println("getServiceInformationHistory.result=" + _getServiceInformationHistory__return);


        }
        {
        System.out.println("Invoking getServiceCaseList...");
        tyler.ecf.v5_0.extensions.wrappers.GetServiceCaseListRequestType _getServiceCaseList_body = null;
        tyler.ecf.v5_0.extensions.wrappers.GetServiceCaseListResponseType _getServiceCaseList__return = port.getServiceCaseList(_getServiceCaseList_body);
        System.out.println("getServiceCaseList.result=" + _getServiceCaseList__return);


        }
        {
        System.out.println("Invoking getPartyList...");
        tyler.ecf.v5_0.extensions.wrappers.GetPartyListRequestType _getPartyList_body = null;
        tyler.ecf.v5_0.extensions.wrappers.GetPartyListResponseType _getPartyList__return = port.getPartyList(_getPartyList_body);
        System.out.println("getPartyList.result=" + _getPartyList__return);


        }

        System.exit(0);
    }

}
