package tyler.ecf.v5_0.extensions.tylerfilingreviewmde;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.1
 * 2023-07-26T11:44:22.014-04:00
 * Generated source version: 4.0.1
 *
 */
@WebServiceClient(name = "TylerFilingReviewMDEService",
                  wsdlLocation = "file:illinois-ecf5-TylerFilingReviewMDEService.wsdl",
                  targetNamespace = "urn:tyler:ecf:v5.0:extensions:TylerFilingReviewMDE")
public class TylerFilingReviewMDEService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:tyler:ecf:v5.0:extensions:TylerFilingReviewMDE", "TylerFilingReviewMDEService");
    public final static QName TylerFilingReviewMDE = new QName("urn:tyler:ecf:v5.0:extensions:TylerFilingReviewMDE", "TylerFilingReviewMDE");
    static {
        URL url = null;
        try {
            url = new URL("file:illinois-ecf5-TylerFilingReviewMDEService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TylerFilingReviewMDEService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:illinois-ecf5-TylerFilingReviewMDEService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TylerFilingReviewMDEService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TylerFilingReviewMDEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TylerFilingReviewMDEService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TylerFilingReviewMDEService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TylerFilingReviewMDEService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TylerFilingReviewMDEService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TylerFilingReviewMDE
     */
    @WebEndpoint(name = "TylerFilingReviewMDE")
    public TylerFilingReviewMDE getTylerFilingReviewMDE() {
        return super.getPort(TylerFilingReviewMDE, TylerFilingReviewMDE.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TylerFilingReviewMDE
     */
    @WebEndpoint(name = "TylerFilingReviewMDE")
    public TylerFilingReviewMDE getTylerFilingReviewMDE(WebServiceFeature... features) {
        return super.getPort(TylerFilingReviewMDE, TylerFilingReviewMDE.class, features);
    }

}
