
package tyler.ecf.v5_0.extensions.tylerfilingreviewmde;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.1
 * 2023-07-26T11:44:21.925-04:00
 * Generated source version: 4.0.1
 *
 */
public final class TylerFilingReviewMDE_TylerFilingReviewMDE_Client {

    private static final QName SERVICE_NAME = new QName("urn:tyler:ecf:v5.0:extensions:TylerFilingReviewMDE", "TylerFilingReviewMDEService");

    private TylerFilingReviewMDE_TylerFilingReviewMDE_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TylerFilingReviewMDEService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TylerFilingReviewMDEService ss = new TylerFilingReviewMDEService(wsdlURL, SERVICE_NAME);
        TylerFilingReviewMDE port = ss.getTylerFilingReviewMDE();

        {
        System.out.println("Invoking getBatchList...");
        tyler.ecf.v5_0.extensions.wrappers.GetBatchListRequestType _getBatchList_body = null;
        tyler.ecf.v5_0.extensions.wrappers.GetBatchListResponseType _getBatchList__return = port.getBatchList(_getBatchList_body);
        System.out.println("getBatchList.result=" + _getBatchList__return);


        }
        {
        System.out.println("Invoking getBatchDetail...");
        tyler.ecf.v5_0.extensions.wrappers.GetBatchDetailRequestType _getBatchDetail_body = null;
        tyler.ecf.v5_0.extensions.wrappers.GetBatchDetailResponseType _getBatchDetail__return = port.getBatchDetail(_getBatchDetail_body);
        System.out.println("getBatchDetail.result=" + _getBatchDetail__return);


        }
        {
        System.out.println("Invoking getFilingService...");
        tyler.ecf.v5_0.extensions.wrappers.GetFilingServiceRequestType _getFilingService_body = null;
        tyler.ecf.v5_0.extensions.wrappers.GetFilingServiceResponseType _getFilingService__return = port.getFilingService(_getFilingService_body);
        System.out.println("getFilingService.result=" + _getFilingService__return);


        }
        {
        System.out.println("Invoking getServiceTypes...");
        tyler.ecf.v5_0.extensions.wrappers.GetServiceTypesRequestType _getServiceTypes_body = null;
        tyler.ecf.v5_0.extensions.wrappers.GetServiceTypesResponseType _getServiceTypes__return = port.getServiceTypes(_getServiceTypes_body);
        System.out.println("getServiceTypes.result=" + _getServiceTypes__return);


        }

        System.exit(0);
    }

}
