package tyler.efm.wsdl.webservicesprofile_implementation_4_0;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import oasis.names.tc.legalxml_courtfiling.wsdl.webservicesprofile_definitions_4_0.CourtRecordMDEPort;

/**
 * This class was generated by Apache CXF 3.5.0-SNAPSHOT-3e40a2387febaf00f47fe893d97ffdf63aaa4626
 * 2021-07-21T17:05:34.950-04:00
 * Generated source version: 3.5.0-SNAPSHOT
 *
 */
@WebServiceClient(name = "CourtRecordMDEService",
                  wsdlLocation = "classpath:wsdl/filingreview/ECF-4.0-CourtRecordMDEService.wsdl",
                  targetNamespace = "urn:tyler:efm:wsdl:WebServicesProfile-Implementation-4.0")
public class CourtRecordMDEService extends Service {

    public final static QName SERVICE = new QName("urn:tyler:efm:wsdl:WebServicesProfile-Implementation-4.0", "CourtRecordMDEService");
    public final static QName CourtRecordMDEPort = new QName("urn:tyler:efm:wsdl:WebServicesProfile-Implementation-4.0", "CourtRecordMDEPort");

    public CourtRecordMDEService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CourtRecordMDEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourtRecordMDEService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CourtRecordMDEService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CourtRecordMDEPort
     */
    @WebEndpoint(name = "CourtRecordMDEPort")
    public CourtRecordMDEPort getCourtRecordMDEPort() {
        return super.getPort(CourtRecordMDEPort, CourtRecordMDEPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourtRecordMDEPort
     */
    @WebEndpoint(name = "CourtRecordMDEPort")
    public CourtRecordMDEPort getCourtRecordMDEPort(WebServiceFeature... features) {
        return super.getPort(CourtRecordMDEPort, CourtRecordMDEPort.class, features);
    }

}
