package tyler.efm.wsdl.webservicesprofile_implementation_4_0;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;
import oasis.names.tc.legalxml_courtfiling.wsdl.webservicesprofile_definitions_4_0.FilingReviewMDEPort;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-06-09T14:37:19.465-04:00
 * Generated source version: 3.5.2
 *
 */
@WebServiceClient(name = "FilingReviewMDEService",
                  wsdlLocation = "classpath:wsdl/stage/illinois-ECF-4.0-FilingReviewMDEService.wsdl",
                  targetNamespace = "urn:tyler:efm:wsdl:WebServicesProfile-Implementation-4.0")
public class FilingReviewMDEService extends Service {

    public final static QName SERVICE = new QName("urn:tyler:efm:wsdl:WebServicesProfile-Implementation-4.0", "FilingReviewMDEService");
    public final static QName FilingReviewMDEPort = new QName("urn:tyler:efm:wsdl:WebServicesProfile-Implementation-4.0", "FilingReviewMDEPort");

    public FilingReviewMDEService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FilingReviewMDEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FilingReviewMDEService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FilingReviewMDEService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns FilingReviewMDEPort
     */
    @WebEndpoint(name = "FilingReviewMDEPort")
    public FilingReviewMDEPort getFilingReviewMDEPort() {
        return super.getPort(FilingReviewMDEPort, FilingReviewMDEPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FilingReviewMDEPort
     */
    @WebEndpoint(name = "FilingReviewMDEPort")
    public FilingReviewMDEPort getFilingReviewMDEPort(WebServiceFeature... features) {
        return super.getPort(FilingReviewMDEPort, FilingReviewMDEPort.class, features);
    }

}
