package tyler.efm.wsdl.webservicesprofile_implementation_4_0;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import oasis.names.tc.legalxml_courtfiling.wsdl.webservicesprofile_definitions_4_0.ServiceMDEPort;

/**
 * This class was generated by Apache CXF 3.5.0-SNAPSHOT-3e40a2387febaf00f47fe893d97ffdf63aaa4626
 * 2021-07-21T17:06:29.346-04:00
 * Generated source version: 3.5.0-SNAPSHOT
 *
 */
@WebServiceClient(name = "ServiceMDEService",
                  wsdlLocation = "classpath:wsdl/filingreview/ECF-4.0-ServiceMDEService.wsdl",
                  targetNamespace = "urn:tyler:efm:wsdl:WebServicesProfile-Implementation-4.0")
public class ServiceMDEService extends Service {

    public final static QName SERVICE = new QName("urn:tyler:efm:wsdl:WebServicesProfile-Implementation-4.0", "ServiceMDEService");
    public final static QName ServiceMDEPort = new QName("urn:tyler:efm:wsdl:WebServicesProfile-Implementation-4.0", "ServiceMDEPort");

    public ServiceMDEService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceMDEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceMDEService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServiceMDEService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ServiceMDEPort
     */
    @WebEndpoint(name = "ServiceMDEPort")
    public ServiceMDEPort getServiceMDEPort() {
        return super.getPort(ServiceMDEPort, ServiceMDEPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceMDEPort
     */
    @WebEndpoint(name = "ServiceMDEPort")
    public ServiceMDEPort getServiceMDEPort(WebServiceFeature... features) {
        return super.getPort(ServiceMDEPort, ServiceMDEPort.class, features);
    }

}
