version: "3.9"

services:
  efspjava-test:
    build:
      context: .
    # Necessary b/c docassemble is external to the docker network
    ports:
      - target: 9009
        published: 9100
      - target: 9000
        published: 9101
    command: /bin/sh /usr/src/app/docker_integration_test.sh
    env_file: .env.test
    depends_on:
      - "db"
    volumes:
      - type: bind
        source: ./src/main/config
        target: /tmp/tls_certs
      # Uncomment this for debugging: you can get exact SOAP envelopes being
      # sent by running wireshark locally
      - type: bind
        source: .
        target: /tmp/secrets
      - type: bind
        source: target
        target: /tmp/jacoco
    deploy:
      resources:
        limits:
          memory: 4G
  db:
    image: "postgres:14"
    shm_size: 128MB
    env_file: .env.test
    volumes:
      - data-volume:/var/lib/postgresql/data

volumes:
  data-volume:
