services:
  efspjava:
    build:
      context: .
      target: release
    # Necessary b/c docassemble is external to the docker network
    ports:
      - target: 9009
        published: 80
      - target: 9000
        published: 443
    env_file: .env
    depends_on:
      - "db"
    volumes:
      - type: bind
        source: ./proxyserver/src/main/config
        target: /tmp/tls_certs
    deploy:
      resources:
        limits:
          memory: 4G
  db:
    image: "postgres:14"
    shm_size: 256m
    env_file: .env
    volumes:
      - data-volume:/var/lib/postgresql/data
      - ./postgres-config:/etc/postgresql

volumes:
  data-volume:
