<?xml version="1.0" encoding="UTF-8"?>

<definitions targetNamespace="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtRecordMDE" xmlns:wsmp="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtRecordMDE" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/">
	<import namespace="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtRecordMDE" location="ecf5-CourtRecordMDE.wsdl"/>
	<!--import location="ecf5-full-90b994a1b7805590.xsd" namespace="urn:tyler:ecf:v5.0:extensions:common"/-->
	<import location="ecf5-full-5af175c0454ab847.xsd" namespace="urn:tyler:ecf:v5.0:extensions:criminal"/>
	<import location="ecf5-full-85da63d0dfbf9699.xsd" namespace="urn:tyler:ecf:v5.0:extensions:massachusetts"/>
	<import location="ecf5-full-f80a207221f28385.xsd" namespace="urn:tyler:ecf:v5.0:extensions:taxdelinquency"/>
	<service name="CourtRecordMDEService">
		<port name="CourtRecordMDE" binding="wsmp:CourtRecordMDESoap">
			<soap:address location="https://illinois-stage.tylertech.cloud/efm/v5/courtrecordservice.svc"/>
		</port>
	</service>
</definitions>