<?xml version="1.0" encoding="UTF-8"?>

<definitions targetNamespace="urn:tyler:ecf:v5.0:extensions:TylerFilingAssemblyMDE" xmlns:wsmp="urn:tyler:ecf:v5.0:extensions:TylerFilingAssemblyMDE" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/">
	<import namespace="urn:tyler:ecf:v5.0:extensions:TylerFilingAssemblyMDE" location="ecf5-TylerFilingAssemblyMDE.xsd"/>
	<import location="ecf5-full-5af175c0454ab847.xsd" namespace="urn:tyler:ecf:v5.0:extensions:criminal"/>
	<import location="ecf5-full-85da63d0dfbf9699.xsd" namespace="urn:tyler:ecf:v5.0:extensions:massachusetts"/>
	<import location="ecf5-full-f80a207221f28385.xsd" namespace="urn:tyler:ecf:v5.0:extensions:taxdelinquency"/>
	<import location="ecf5-full-domestic.xsd" namespace="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/domestic"/>
	<import location="ecf5-full-appellate.xsd" namespace="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/appellate"/>
	<!--import location="ecf5-full-43e22a9b317738fe.xsd" namespace="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/civil"/-->

	<service name="TylerFilingAssemblyMDEService">
		<port name="TylerFilingAssemblyMDE" binding="wsmp:TylerFilingAssemblyMDESoap">
			<soap:address location="https://efile.suffolklitlab.org/jurisdictions/illinois/filingassembly/callbacks/FilingAssemblyMDEPont"/>
		</port>
	</service>
</definitions>
