
package https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0wsdl.servicemde;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.8
 * 2025-11-05T15:26:59.942-05:00
 * Generated source version: 4.0.8
 *
 */
public final class ServiceMDE_ServiceMDE_Client {

    private static final QName SERVICE_NAME = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/ServiceMDE", "ServiceMDEService");

    private ServiceMDE_ServiceMDE_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServiceMDEService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ServiceMDEService ss = new ServiceMDEService(wsdlURL, SERVICE_NAME);
        ServiceMDE port = ss.getServiceMDE();

        {
        System.out.println("Invoking serveProcess...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.ServeProcessRequestType _serveProcess_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.ServeProcessResponseType _serveProcess__return = port.serveProcess(_serveProcess_body);
        System.out.println("serveProcess.result=" + _serveProcess__return);


        }
        {
        System.out.println("Invoking serveFiling...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.ServeFilingRequestType _serveFiling_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.ServeFilingResponseType _serveFiling__return = port.serveFiling(_serveFiling_body);
        System.out.println("serveFiling.result=" + _serveFiling__return);


        }

        System.exit(0);
    }

}
