//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.16 at 04:29:27 PM UTC 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://docs.oasis-open.org/codelist/ns/genericode/1.0/")
package org.oasis_open.docs.codelist.ns.genericode._1;
