
package https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0wsdl.courtrecordmde;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.1
 * 2023-05-31T17:28:32.506-04:00
 * Generated source version: 4.0.1
 *
 */
public final class CourtRecordMDE_CourtRecordMDE_Client {

    private static final QName SERVICE_NAME = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtRecordMDE", "CourtRecordMDEService");

    private CourtRecordMDE_CourtRecordMDE_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CourtRecordMDEService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CourtRecordMDEService ss = new CourtRecordMDEService(wsdlURL, SERVICE_NAME);
        CourtRecordMDE port = ss.getCourtRecordMDE();

        {
        System.out.println("Invoking recordDocketing...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.RecordDocketingRequestType _recordDocketing_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.RecordDocketingResponseType _recordDocketing__return = port.recordDocketing(_recordDocketing_body);
        System.out.println("recordDocketing.result=" + _recordDocketing__return);


        }
        {
        System.out.println("Invoking getCaseList...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.GetCaseListRequestType _getCaseList_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.GetCaseListResponseType _getCaseList__return = port.getCaseList(_getCaseList_body);
        System.out.println("getCaseList.result=" + _getCaseList__return);


        }
        {
        System.out.println("Invoking getDocument...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.GetDocumentRequestType _getDocument_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.GetDocumentResponseType _getDocument__return = port.getDocument(_getDocument_body);
        System.out.println("getDocument.result=" + _getDocument__return);


        }
        {
        System.out.println("Invoking getServiceInformation...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.GetServiceInformationRequestType _getServiceInformation_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.GetServiceInformationResponseType _getServiceInformation__return = port.getServiceInformation(_getServiceInformation_body);
        System.out.println("getServiceInformation.result=" + _getServiceInformation__return);


        }
        {
        System.out.println("Invoking allocateCourtDate...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.AllocateCourtDateRequestType _allocateCourtDate_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.AllocateCourtDateResponseType _allocateCourtDate__return = port.allocateCourtDate(_allocateCourtDate_body);
        System.out.println("allocateCourtDate.result=" + _allocateCourtDate__return);


        }
        {
        System.out.println("Invoking getCase...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.GetCaseRequestType _getCase_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.GetCaseResponseType _getCase__return = port.getCase(_getCase_body);
        System.out.println("getCase.result=" + _getCase__return);


        }
        {
        System.out.println("Invoking documentStampInformation...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.DocumentStampInformationRequestType _documentStampInformation_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.DocumentStampInformationResponseType _documentStampInformation__return = port.documentStampInformation(_documentStampInformation_body);
        System.out.println("documentStampInformation.result=" + _documentStampInformation__return);


        }

        System.exit(0);
    }

}
