
package https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0wsdl.filingreviewmde;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.8
 * 2025-11-05T15:26:49.095-05:00
 * Generated source version: 4.0.8
 *
 */
public final class FilingReviewMDE_FilingReviewMDE_Client {

    private static final QName SERVICE_NAME = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/FilingReviewMDE", "FilingReviewMDEService");

    private FilingReviewMDE_FilingReviewMDE_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FilingReviewMDEService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        FilingReviewMDEService ss = new FilingReviewMDEService(wsdlURL, SERVICE_NAME);
        FilingReviewMDE port = ss.getFilingReviewMDE();

        {
        System.out.println("Invoking notifyDocumentStampInformation...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.NotifyDocumentStampInformationRequestType _notifyDocumentStampInformation_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.NotifyDocumentStampInformationResponseType _notifyDocumentStampInformation__return = port.notifyDocumentStampInformation(_notifyDocumentStampInformation_body);
        System.out.println("notifyDocumentStampInformation.result=" + _notifyDocumentStampInformation__return);


        }
        {
        System.out.println("Invoking reviewFiling...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.ReviewFilingRequestType _reviewFiling_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.ReviewFilingResponseType _reviewFiling__return = port.reviewFiling(_reviewFiling_body);
        System.out.println("reviewFiling.result=" + _reviewFiling__return);


        }
        {
        System.out.println("Invoking getFeesCalculation...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.GetFeesCalculationRequestType _getFeesCalculation_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.GetFeesCalculationResponseType _getFeesCalculation__return = port.getFeesCalculation(_getFeesCalculation_body);
        System.out.println("getFeesCalculation.result=" + _getFeesCalculation__return);


        }
        {
        System.out.println("Invoking cancelFiling...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.CancelFilingRequestType _cancelFiling_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.CancelFilingResponseType _cancelFiling__return = port.cancelFiling(_cancelFiling_body);
        System.out.println("cancelFiling.result=" + _cancelFiling__return);


        }
        {
        System.out.println("Invoking getFilingStatus...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.GetFilingStatusRequestType _getFilingStatus_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.GetFilingStatusResponseType _getFilingStatus__return = port.getFilingStatus(_getFilingStatus_body);
        System.out.println("getFilingStatus.result=" + _getFilingStatus__return);


        }
        {
        System.out.println("Invoking notifyDocketingComplete...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.NotifyDocketingCompleteRequestType _notifyDocketingComplete_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.NotifyDocketingCompleteResponseType _notifyDocketingComplete__return = port.notifyDocketingComplete(_notifyDocketingComplete_body);
        System.out.println("notifyDocketingComplete.result=" + _notifyDocketingComplete__return);


        }
        {
        System.out.println("Invoking getFilingList...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.GetFilingListRequestType _getFilingList_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.GetFilingListResponseType _getFilingList__return = port.getFilingList(_getFilingList_body);
        System.out.println("getFilingList.result=" + _getFilingList__return);


        }

        System.exit(0);
    }

}
