<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="EfmFirmService" targetNamespace="urn:tyler:efm:services"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="urn:tyler:efm:services">
	<wsdl:import location="Base-EFMFirmServiceSingle.svc.wsdl"
		namespace="urn:tyler:efm:services" />
    <wsdl:service name="EfmFirmService">
        <wsdl:port name="BasicHttpBinding_IEfmFirmService"
            binding="tns:BasicHttpBinding_IEfmFirmService">
            <soap:address location="https://illinois-stage.tylertech.cloud/EFM/EFMFirmService.svc" />
        </wsdl:port>
        <wsdl:port name="BasicHttpBinding_IEfmFirmService1"
            binding="tns:BasicHttpBinding_IEfmFirmService1">
            <soap:address
                location="https://illinois-stage.tylertech.cloud/EFM/EFMFirmService.svc/test" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>