package https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0wsdl.courtschedulingmde;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.8
 * 2025-11-05T15:39:12.512-05:00
 * Generated source version: 4.0.8
 *
 */
@WebServiceClient(name = "CourtSchedulingMDEService",
                  wsdlLocation = "file:../stage/illinois-ECF5-CourtSchedulingMDEService.wsdl",
                  targetNamespace = "https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtSchedulingMDE")
public class CourtSchedulingMDEService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtSchedulingMDE", "CourtSchedulingMDEService");
    public static final QName CourtSchedulingMDE = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtSchedulingMDE", "CourtSchedulingMDE");
    static {
        URL url = null;
        try {
            url = URI.create("file:../stage/illinois-ECF5-CourtSchedulingMDEService.wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CourtSchedulingMDEService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:../stage/illinois-ECF5-CourtSchedulingMDEService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CourtSchedulingMDEService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CourtSchedulingMDEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourtSchedulingMDEService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CourtSchedulingMDEService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CourtSchedulingMDEService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CourtSchedulingMDEService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CourtSchedulingMDE
     */
    @WebEndpoint(name = "CourtSchedulingMDE")
    public CourtSchedulingMDE getCourtSchedulingMDE() {
        return super.getPort(CourtSchedulingMDE, CourtSchedulingMDE.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourtSchedulingMDE
     */
    @WebEndpoint(name = "CourtSchedulingMDE")
    public CourtSchedulingMDE getCourtSchedulingMDE(WebServiceFeature... features) {
        return super.getPort(CourtSchedulingMDE, CourtSchedulingMDE.class, features);
    }

}
