
package https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0wsdl.courtschedulingmde;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.8
 * 2025-11-05T15:39:12.466-05:00
 * Generated source version: 4.0.8
 *
 */
public final class CourtSchedulingMDE_CourtSchedulingMDE_Client {

    private static final QName SERVICE_NAME = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtSchedulingMDE", "CourtSchedulingMDEService");

    private CourtSchedulingMDE_CourtSchedulingMDE_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CourtSchedulingMDEService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CourtSchedulingMDEService ss = new CourtSchedulingMDEService(wsdlURL, SERVICE_NAME);
        CourtSchedulingMDE port = ss.getCourtSchedulingMDE();

        {
        System.out.println("Invoking getCourtSchedule...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.GetCourtScheduleRequestType _getCourtSchedule_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.GetCourtScheduleResponseType _getCourtSchedule__return = port.getCourtSchedule(_getCourtSchedule_body);
        System.out.println("getCourtSchedule.result=" + _getCourtSchedule__return);


        }
        {
        System.out.println("Invoking notifyCourtDate...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.NotifyCourtDateRequestType _notifyCourtDate_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.NotifyCourtDateResponseType _notifyCourtDate__return = port.notifyCourtDate(_notifyCourtDate_body);
        System.out.println("notifyCourtDate.result=" + _notifyCourtDate__return);


        }
        {
        System.out.println("Invoking reserveCourtDate...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.ReserveCourtDateRequestType _reserveCourtDate_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.ReserveCourtDateResponseType _reserveCourtDate__return = port.reserveCourtDate(_reserveCourtDate_body);
        System.out.println("reserveCourtDate.result=" + _reserveCourtDate__return);


        }
        {
        System.out.println("Invoking requestCourtDate...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.RequestCourtDateRequestType _requestCourtDate_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wrappers.RequestCourtDateResponseType _requestCourtDate__return = port.requestCourtDate(_requestCourtDate_body);
        System.out.println("requestCourtDate.result=" + _requestCourtDate__return);


        }

        System.exit(0);
    }

}
