
package tyler.ecf.v5_0.extensions.tylercourtschedulingmde;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.8
 * 2025-11-05T15:27:55.560-05:00
 * Generated source version: 4.0.8
 *
 */
public final class TylerCourtSchedulingMDE_TylerCourtSchedulingMDE_Client {

    private static final QName SERVICE_NAME = new QName("urn:tyler:ecf:v5.0:extensions:TylerCourtSchedulingMDE", "TylerCourtSchedulingMDEService");

    private TylerCourtSchedulingMDE_TylerCourtSchedulingMDE_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TylerCourtSchedulingMDEService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TylerCourtSchedulingMDEService ss = new TylerCourtSchedulingMDEService(wsdlURL, SERVICE_NAME);
        TylerCourtSchedulingMDE port = ss.getTylerCourtSchedulingMDE();

        {
        System.out.println("Invoking getReturnDate...");
        tyler.ecf.v5_0.extensions.wrappers.GetReturnDateRequestType _getReturnDate_body = null;
        tyler.ecf.v5_0.extensions.wrappers.GetReturnDateResponseType _getReturnDate__return = port.getReturnDate(_getReturnDate_body);
        System.out.println("getReturnDate.result=" + _getReturnDate__return);


        }

        System.exit(0);
    }

}
