<?xml version="1.0" encoding="UTF-8"?>

<definitions targetNamespace="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtSchedulingMDE" xmlns:wsmp="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtSchedulingMDE" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/">
	
	<import location="../base/CourtSchedulingMDE.wsdl" namespace="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtSchedulingMDE"/>
	<import location="../base/ecfv5-criminal-extension.xsd" namespace="urn:tyler:ecf:v5.0:extensions:criminal"/>
	<import location="../base/ecfv5-massachusetts-extension.xsd" namespace="urn:tyler:ecf:v5.0:extensions:massachusetts"/>
	<import location="../base/ecfv5-taxdelinquency-extension.xsd" namespace="urn:tyler:ecf:v5.0:extensions:taxdelinquency"/>
	<import location="../base/ecfv5-43e22a9b317738fe.xsd" namespace="https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/civil"/>
	<service name="CourtSchedulingMDEService">
		<port name="CourtSchedulingMDE" binding="wsmp:CourtSchedulingMDESoap">
			<soap:address location="https://illinois-stage.tylertech.cloud/efm/v5/courtschedulingservice.svc"/>
		</port>
	</service>
</definitions>