<?xml version="1.0" encoding="UTF-8"?>

<definitions targetNamespace="urn:tyler:ecf:v5.0:extensions:TylerFilingReviewMDE" xmlns:wsmp="urn:tyler:ecf:v5.0:extensions:TylerFilingReviewMDE" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/">
	<import namespace="urn:tyler:ecf:v5.0:extensions:TylerFilingReviewMDE" location="../base/TylerFilingReviewMDE.wsdl"/>
	<!--import location="ecf5-full-90b994a1b7805590.xsd" namespace="urn:tyler:ecf:v5.0:extensions:common"/-->
	<import location="../base/ecfv5-criminal-extension.xsd" namespace="urn:tyler:ecf:v5.0:extensions:criminal"/>
	<import location="../base/ecfv5-massachusetts-extension.xsd" namespace="urn:tyler:ecf:v5.0:extensions:massachusetts"/>
	<import location="../base/ecfv5-taxdelinquency-extension.xsd" namespace="urn:tyler:ecf:v5.0:extensions:taxdelinquency"/>
	<service name="TylerFilingReviewMDEService">
		<port name="TylerFilingReviewMDE" binding="wsmp:TylerFilingReviewMDESoap">
			<soap:address location="https://illinois-stage.tylertech.cloud/efm/v5/filingreviewservice.svc" />
		</port>
	</service>
</definitions>