package tyler.efm;

import java.net.URL;
import javax.xml.namespace.QName;

import edu.suffolk.litlab.efsp.tyler.TylerVersion;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was originally generated by Apache CXF 4.0.8
 * 2025-06-13T15:28:22.368-04:00
 * Generated source version: 4.0.8
 *
 */
@WebServiceClient(name = "EfmFirmService",
                  wsdlLocation = "file:resources/wsdl/v2025_0/illinois-EFMFirmServiceSingle.svc.wsdl",
                  targetNamespace = "urn:tyler:efm:services")
public class EfmFirmService extends Service {

    public static final QName SERVICE = new QName("urn:tyler:efm:services", "EfmFirmService");
    public static final QName BasicHttpBindingIEfmFirmService = new QName("urn:tyler:efm:services", "BasicHttpBinding_IEfmFirmService");

    private final TylerVersion version;

    public EfmFirmService(URL wsdlLocation, TylerVersion version) {
        super(wsdlLocation, SERVICE);
        this.version = version;
    }

    public TylerVersion getVersion() {
        return version;
    }

    /**
     *
     * @return
     *     returns IEfmFirmService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEfmFirmService")
    public IEfmFirmService getBasicHttpBindingIEfmFirmService() {
        return super.getPort(BasicHttpBindingIEfmFirmService, IEfmFirmService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEfmFirmService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEfmFirmService")
    public IEfmFirmService getBasicHttpBindingIEfmFirmService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIEfmFirmService, IEfmFirmService.class, features);
    }

}
