package tyler.efm;

import java.net.URL;
import javax.xml.namespace.QName;

import edu.suffolk.litlab.efsp.tyler.TylerVersion;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import tyler.efm.latest.services.IEfmUserService;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.8
 * 2025-06-13T15:28:20.717-04:00
 * Generated source version: 4.0.8
 *
 */
@WebServiceClient(name = "EfmUserService",
                  targetNamespace = "urn:tyler:efm:services")
public class EfmUserService extends Service {

    public static final QName SERVICE = new QName("urn:tyler:efm:services", "EfmUserService");
    public static final QName BasicHttpBindingIEfmUserService = new QName("urn:tyler:efm:services", "BasicHttpBinding_IEfmUserService");
    public static final QName BasicHttpBindingIEfmUserService1 = new QName("urn:tyler:efm:services", "BasicHttpBinding_IEfmUserService1");

    private final TylerVersion version;

    public EfmUserService(URL wsdlLocation, TylerVersion version) {
        super(wsdlLocation, SERVICE);
        this.version = version;
    }

    public TylerVersion getVersion() {
        return version;
    }


    /**
     *
     * @return
     *     returns IEfmUserService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEfmUserService")
    public IEfmUserService getBasicHttpBindingIEfmUserService() {
        return super.getPort(BasicHttpBindingIEfmUserService, IEfmUserService.class);
    }

    /**
     *
     * @return
     *     returns IEfmUserService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEfmUserService")
    public tyler.efm.v2022_1.services.IEfmUserService getBasicHttpBindingV2022IEfmUserService() {
        return super.getPort(BasicHttpBindingIEfmUserService, tyler.efm.v2022_1.services.IEfmUserService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEfmUserService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEfmUserService")
    public IEfmUserService getBasicHttpBindingIEfmUserService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIEfmUserService, IEfmUserService.class, features);
    }
}
