package tyler.ecf.v5_0.extensions.tylercourtrecordmde;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.1
 * 2023-06-02T12:00:05.998-04:00
 * Generated source version: 4.0.1
 *
 */
@WebServiceClient(name = "TylerCourtRecordMDEService",
                  wsdlLocation = "classpath:wsdl/stage/illinois-ecf5-TylerCourtRecordMDEService.wsdl",
                  targetNamespace = "urn:tyler:ecf:v5.0:extensions:TylerCourtRecordMDE")
public class TylerCourtRecordMDEService extends Service {

    public final static QName SERVICE = new QName("urn:tyler:ecf:v5.0:extensions:TylerCourtRecordMDE", "TylerCourtRecordMDEService");
    public final static QName TTylerCourtRecordMDE = new QName("urn:tyler:ecf:v5.0:extensions:TylerCourtRecordMDE", "TTylerCourtRecordMDE");

    public TylerCourtRecordMDEService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TylerCourtRecordMDEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TylerCourtRecordMDEService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TylerCourtRecordMDEService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TylerCourtRecordMDE
     */
    @WebEndpoint(name = "TTylerCourtRecordMDE")
    public TylerCourtRecordMDE getTTylerCourtRecordMDE() {
        return super.getPort(TTylerCourtRecordMDE, TylerCourtRecordMDE.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TylerCourtRecordMDE
     */
    @WebEndpoint(name = "TTylerCourtRecordMDE")
    public TylerCourtRecordMDE getTTylerCourtRecordMDE(WebServiceFeature... features) {
        return super.getPort(TTylerCourtRecordMDE, TylerCourtRecordMDE.class, features);
    }

}
