package https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0wsdl.courtschedulingmde;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.1
 * 2023-09-18T14:40:52.327-04:00
 * Generated source version: 4.0.1
 *
 */
@WebServiceClient(name = "CourtSchedulingMDEService",
                  wsdlLocation = "file:illinois-ecf5-CourtSchedulingMDEService.wsdl",
                  targetNamespace = "https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtSchedulingMDE")
public class CourtSchedulingMDEService extends Service {

    public final static QName SERVICE = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtSchedulingMDE", "CourtSchedulingMDEService");
    public final static QName CourtSchedulingMDE = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtSchedulingMDE", "CourtSchedulingMDE");

    public CourtSchedulingMDEService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CourtSchedulingMDEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourtSchedulingMDEService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CourtSchedulingMDEService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CourtSchedulingMDE
     */
    @WebEndpoint(name = "CourtSchedulingMDE")
    public CourtSchedulingMDE getCourtSchedulingMDE() {
        return super.getPort(CourtSchedulingMDE, CourtSchedulingMDE.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourtSchedulingMDE
     */
    @WebEndpoint(name = "CourtSchedulingMDE")
    public CourtSchedulingMDE getCourtSchedulingMDE(WebServiceFeature... features) {
        return super.getPort(CourtSchedulingMDE, CourtSchedulingMDE.class, features);
    }

}
