
package tyler.ecf.v5_0.extensions.tylerfilingassemblymde;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.8
 * 2025-11-05T15:38:10.421-05:00
 * Generated source version: 4.0.8
 *
 */
public final class TylerFilingAssemblyMDE_TylerFilingAssemblyMDE_Client {

    private static final QName SERVICE_NAME = new QName("urn:tyler:ecf:v5.0:extensions:TylerFilingAssemblyMDE", "TylerFilingAssemblyMDEService");

    private TylerFilingAssemblyMDE_TylerFilingAssemblyMDE_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TylerFilingAssemblyMDEService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TylerFilingAssemblyMDEService ss = new TylerFilingAssemblyMDEService(wsdlURL, SERVICE_NAME);
        TylerFilingAssemblyMDE port = ss.getTylerFilingAssemblyMDE();

        {
        System.out.println("Invoking notifyEvent...");
        tyler.ecf.v5_0.extensions.wrappers.NotifyEventRequestType _notifyEvent_body = null;
        tyler.ecf.v5_0.extensions.wrappers.NotifyEventResponseType _notifyEvent__return = port.notifyEvent(_notifyEvent_body);
        System.out.println("notifyEvent.result=" + _notifyEvent__return);


        }
        {
        System.out.println("Invoking captureFees...");
        tyler.ecf.v5_0.extensions.wrappers.CaptureFeesRequestType _captureFees_body = null;
        tyler.ecf.v5_0.extensions.wrappers.CaptureFeesResponseType _captureFees__return = port.captureFees(_captureFees_body);
        System.out.println("captureFees.result=" + _captureFees__return);


        }
        {
        System.out.println("Invoking notifyBatchComplete...");
        tyler.ecf.v5_0.extensions.wrappers.NotifyBatchCompleteRequestType _notifyBatchComplete_body = null;
        tyler.ecf.v5_0.extensions.wrappers.NotifyBatchCompleteResponseType _notifyBatchComplete__return = port.notifyBatchComplete(_notifyBatchComplete_body);
        System.out.println("notifyBatchComplete.result=" + _notifyBatchComplete__return);


        }
        {
        System.out.println("Invoking notifyServiceComplete...");
        tyler.ecf.v5_0.extensions.wrappers.NotifyServiceCompleteRequestType _notifyServiceComplete_body = null;
        tyler.ecf.v5_0.extensions.wrappers.NotifyServiceCompleteResponseType _notifyServiceComplete__return = port.notifyServiceComplete(_notifyServiceComplete_body);
        System.out.println("notifyServiceComplete.result=" + _notifyServiceComplete__return);


        }
        {
        System.out.println("Invoking updateFees...");
        tyler.ecf.v5_0.extensions.wrappers.UpdateFeesRequestType _updateFees_body = null;
        tyler.ecf.v5_0.extensions.wrappers.UpdateFeesResponseType _updateFees__return = port.updateFees(_updateFees_body);
        System.out.println("updateFees.result=" + _updateFees__return);


        }
        {
        System.out.println("Invoking notifyEnvelopeComplete...");
        tyler.ecf.v5_0.extensions.wrappers.NotifyEnvelopeCompleteRequestType _notifyEnvelopeComplete_body = null;
        tyler.ecf.v5_0.extensions.wrappers.NotifyEnvelopeCompleteResponseType _notifyEnvelopeComplete__return = port.notifyEnvelopeComplete(_notifyEnvelopeComplete_body);
        System.out.println("notifyEnvelopeComplete.result=" + _notifyEnvelopeComplete__return);


        }

        System.exit(0);
    }

}
