package tyler.ecf.v5_0.extensions.tylerfilingassemblymde;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.8
 * 2025-11-05T15:38:10.468-05:00
 * Generated source version: 4.0.8
 *
 */
@WebServiceClient(name = "TylerFilingAssemblyMDEService",
                  wsdlLocation = "file:../stage/illinois-ECF5-TylerFilingAssemblyMDEService.wsdl",
                  targetNamespace = "urn:tyler:ecf:v5.0:extensions:TylerFilingAssemblyMDE")
public class TylerFilingAssemblyMDEService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("urn:tyler:ecf:v5.0:extensions:TylerFilingAssemblyMDE", "TylerFilingAssemblyMDEService");
    public static final QName TylerFilingAssemblyMDE = new QName("urn:tyler:ecf:v5.0:extensions:TylerFilingAssemblyMDE", "TylerFilingAssemblyMDE");
    static {
        URL url = null;
        try {
            url = URI.create("file:../stage/illinois-ECF5-TylerFilingAssemblyMDEService.wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TylerFilingAssemblyMDEService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:../stage/illinois-ECF5-TylerFilingAssemblyMDEService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TylerFilingAssemblyMDEService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TylerFilingAssemblyMDEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TylerFilingAssemblyMDEService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TylerFilingAssemblyMDEService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TylerFilingAssemblyMDEService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TylerFilingAssemblyMDEService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TylerFilingAssemblyMDE
     */
    @WebEndpoint(name = "TylerFilingAssemblyMDE")
    public TylerFilingAssemblyMDE getTylerFilingAssemblyMDE() {
        return super.getPort(TylerFilingAssemblyMDE, TylerFilingAssemblyMDE.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TylerFilingAssemblyMDE
     */
    @WebEndpoint(name = "TylerFilingAssemblyMDE")
    public TylerFilingAssemblyMDE getTylerFilingAssemblyMDE(WebServiceFeature... features) {
        return super.getPort(TylerFilingAssemblyMDE, TylerFilingAssemblyMDE.class, features);
    }

}
