package tyler.efm.services;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-06-09T14:37:23.049-04:00
 * Generated source version: 3.5.2
 *
 */
@WebServiceClient(name = "EfmFirmService",
                  wsdlLocation = "classpath:wsdl/EFMFirmServiceSingle.svc.wsdl",
                  targetNamespace = "urn:tyler:efm:services")
public class EfmFirmService extends Service {

    public final static QName SERVICE = new QName("urn:tyler:efm:services", "EfmFirmService");
    public final static QName BasicHttpBindingIEfmFirmService = new QName("urn:tyler:efm:services", "BasicHttpBinding_IEfmFirmService");
    public final static QName BasicHttpBindingIEfmFirmService1 = new QName("urn:tyler:efm:services", "BasicHttpBinding_IEfmFirmService1");

    public EfmFirmService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EfmFirmService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EfmFirmService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EfmFirmService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IEfmFirmService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEfmFirmService")
    public IEfmFirmService getBasicHttpBindingIEfmFirmService() {
        return super.getPort(BasicHttpBindingIEfmFirmService, IEfmFirmService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEfmFirmService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEfmFirmService")
    public IEfmFirmService getBasicHttpBindingIEfmFirmService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIEfmFirmService, IEfmFirmService.class, features);
    }


    /**
     *
     * @return
     *     returns IEfmFirmService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEfmFirmService1")
    public IEfmFirmService getBasicHttpBindingIEfmFirmService1() {
        return super.getPort(BasicHttpBindingIEfmFirmService1, IEfmFirmService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEfmFirmService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEfmFirmService1")
    public IEfmFirmService getBasicHttpBindingIEfmFirmService1(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIEfmFirmService1, IEfmFirmService.class, features);
    }

}
