
package https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wsdl.courtschedulingmde;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.1-SNAPSHOT-f8d1850dc906be4ac45e2630ae30961b20228938
 * 2023-05-02T17:42:51.517-04:00
 * Generated source version: 4.0.1-SNAPSHOT
 *
 */
public final class CourtSchedulingMDE_CourtSchedulingMDEPort_Client {

    private static final QName SERVICE_NAME = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/WSDL/CourtSchedulingMDE", "CourtSchedulingMDE");

    private CourtSchedulingMDE_CourtSchedulingMDEPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CourtSchedulingMDE_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CourtSchedulingMDE_Service ss = new CourtSchedulingMDE_Service(wsdlURL, SERVICE_NAME);
        CourtSchedulingMDE port = ss.getCourtSchedulingMDEPort();

        {
        System.out.println("Invoking getCourtSchedule...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.messagewrappers.GetCourtScheduleRequestType _getCourtSchedule_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.messagewrappers.GetCourtScheduleResponseType _getCourtSchedule__return = port.getCourtSchedule(_getCourtSchedule_body);
        System.out.println("getCourtSchedule.result=" + _getCourtSchedule__return);


        }
        {
        System.out.println("Invoking reserveCourtDateSync...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.messagewrappers.ReserveCourtDateRequestType _reserveCourtDateSync_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.messagewrappers.ReserveCourtDateSyncResponseType _reserveCourtDateSync__return = port.reserveCourtDateSync(_reserveCourtDateSync_body);
        System.out.println("reserveCourtDateSync.result=" + _reserveCourtDateSync__return);


        }
        {
        System.out.println("Invoking notifyCourtDate...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.messagewrappers.NotifyCourtDateRequestType _notifyCourtDate_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.messagewrappers.NotifyCourtDateResponseType _notifyCourtDate__return = port.notifyCourtDate(_notifyCourtDate_body);
        System.out.println("notifyCourtDate.result=" + _notifyCourtDate__return);


        }
        {
        System.out.println("Invoking getReturnDate...");
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.messagewrappers.ReturnDateRequestType _getReturnDate_body = null;
        https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.messagewrappers.ReturnDateResponseType _getReturnDate__return = port.getReturnDate(_getReturnDate_body);
        System.out.println("getReturnDate.result=" + _getReturnDate__return);


        }

        System.exit(0);
    }

}
