package ecf5;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.8
 * 2025-11-05T15:12:41.425-05:00
 * Generated source version: 4.0.8
 *
 */
@WebServiceClient(name = "CourtPolicyMDEService",
                  wsdlLocation = "file:../stage/illinois-ECF5-CourtPolicyMDEService.wsdl",
                  targetNamespace = "https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtPolicyMDE")
public class CourtPolicyMDEService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtPolicyMDE", "CourtPolicyMDEService");
    public static final QName CourtPolicyMDE = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtPolicyMDE", "CourtPolicyMDE");
    static {
        URL url = null;
        try {
            url = URI.create("file:../stage/illinois-ECF5-CourtPolicyMDEService.wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CourtPolicyMDEService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:../stage/illinois-ECF5-CourtPolicyMDEService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CourtPolicyMDEService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CourtPolicyMDEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourtPolicyMDEService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CourtPolicyMDEService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CourtPolicyMDEService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CourtPolicyMDEService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CourtPolicyMDE
     */
    @WebEndpoint(name = "CourtPolicyMDE")
    public ecf5.v2024_6.https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0wsdl.courtpolicymde.CourtPolicyMDE getCourtPolicyMDE() {
        return super.getPort(CourtPolicyMDE, ecf5.v2024_6.https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0wsdl.courtpolicymde.CourtPolicyMDE.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourtPolicyMDE
     */
    @WebEndpoint(name = "CourtPolicyMDE")
    public ecf5.v2024_6.https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0wsdl.courtpolicymde.CourtPolicyMDE getCourtPolicyMDE(WebServiceFeature... features) {
        return super.getPort(CourtPolicyMDE, ecf5.v2024_6.https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0wsdl.courtpolicymde.CourtPolicyMDE.class, features);
    }

}
