package ecf5;

import ecf5.v2024_6.https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0wsdl.courtrecordmde.CourtRecordMDE;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.8
 * 2025-11-05T15:23:26.656-05:00
 * Generated source version: 4.0.8
 *
 */
@WebServiceClient(name = "CourtRecordMDEService",
                  wsdlLocation = "file:../stage/illinois-ECF5-CourtRecordMDEService.wsdl",
                  targetNamespace = "https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtRecordMDE")
public class CourtRecordMDEService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtRecordMDE", "CourtRecordMDEService");
    public static final QName CourtRecordMDE = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/CourtRecordMDE", "CourtRecordMDE");
    static {
        URL url = null;
        try {
            url = URI.create("file:../stage/illinois-ECF5-CourtRecordMDEService.wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CourtRecordMDEService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:../stage/illinois-ECF5-CourtRecordMDEService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CourtRecordMDEService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CourtRecordMDEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourtRecordMDEService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CourtRecordMDEService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CourtRecordMDEService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CourtRecordMDEService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CourtRecordMDE
     */
    @WebEndpoint(name = "CourtRecordMDE")
    public CourtRecordMDE getCourtRecordMDE() {
        return super.getPort(CourtRecordMDE, CourtRecordMDE.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourtRecordMDE
     */
    @WebEndpoint(name = "CourtRecordMDE")
    public CourtRecordMDE getCourtRecordMDE(WebServiceFeature... features) {
        return super.getPort(CourtRecordMDE, CourtRecordMDE.class, features);
    }

}
