package ecf5;

import ecf5.v2024_6.https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0wsdl.filingreviewmde.FilingReviewMDE;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 4.0.8 2025-11-05T15:26:49.152-05:00 Generated source
 * version: 4.0.8
 */
@WebServiceClient(
    name = "FilingReviewMDEService",
    wsdlLocation = "file:../stage/illinois-ECF5-FilingReviewMDEService.wsdl",
    targetNamespace =
        "https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/FilingReviewMDE")
public class FilingReviewMDEService extends Service {

  public static final URL WSDL_LOCATION;

  public static final QName SERVICE =
      new QName(
          "https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/FilingReviewMDE",
          "FilingReviewMDEService");
  public static final QName FilingReviewMDE =
      new QName(
          "https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/FilingReviewMDE",
          "FilingReviewMDE");

  static {
    URL url = null;
    try {
      url = URI.create("file:../stage/illinois-ECF5-FilingReviewMDEService.wsdl").toURL();
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(FilingReviewMDEService.class.getName())
          .log(
              java.util.logging.Level.INFO,
              "Can not initialize the default wsdl from {0}",
              "file:../stage/illinois-ECF5-FilingReviewMDEService.wsdl");
    }
    WSDL_LOCATION = url;
  }

  public FilingReviewMDEService(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public FilingReviewMDEService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public FilingReviewMDEService() {
    super(WSDL_LOCATION, SERVICE);
  }

  public FilingReviewMDEService(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }

  public FilingReviewMDEService(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  public FilingReviewMDEService(
      URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   * @return returns FilingReviewMDE
   */
  @WebEndpoint(name = "FilingReviewMDE")
  public FilingReviewMDE getFilingReviewMDE() {
    return super.getPort(FilingReviewMDE, FilingReviewMDE.class);
  }

  /**
   * @param features A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.
   *     Supported features not in the <code>features</code> parameter will have their default
   *     values.
   * @return returns FilingReviewMDE
   */
  @WebEndpoint(name = "FilingReviewMDE")
  public FilingReviewMDE getFilingReviewMDE(WebServiceFeature... features) {
    return super.getPort(FilingReviewMDE, FilingReviewMDE.class, features);
  }
}
