package ecf5;


import ecf5.v2024_6.https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0wsdl.servicemde.ServiceMDE;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.8
 * 2025-11-05T15:26:59.986-05:00
 * Generated source version: 4.0.8
 *
 */
@WebServiceClient(name = "ServiceMDEService",
                  wsdlLocation = "file:../stage/illinois-ECF5-ServiceMDEService.wsdl",
                  targetNamespace = "https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/ServiceMDE")
public class ServiceMDEService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/ServiceMDE", "ServiceMDEService");
    public static final QName ServiceMDE = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0WSDL/ServiceMDE", "ServiceMDE");
    static {
        URL url = null;
        try {
            url = URI.create("file:../stage/illinois-ECF5-ServiceMDEService.wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiceMDEService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:../stage/illinois-ECF5-ServiceMDEService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiceMDEService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceMDEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceMDEService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServiceMDEService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServiceMDEService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServiceMDEService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ServiceMDE
     */
    @WebEndpoint(name = "ServiceMDE")
    public ServiceMDE getServiceMDE() {
        return super.getPort(ServiceMDE, ServiceMDE.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceMDE
     */
    @WebEndpoint(name = "ServiceMDE")
    public ServiceMDE getServiceMDE(WebServiceFeature... features) {
        return super.getPort(ServiceMDE, ServiceMDE.class, features);
    }

}
