package ecf5;

import ecf5.v2024_6.tyler.ecf.v5_0.extensions.tylercourtrecordmde.TylerCourtRecordMDE;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 4.0.8 2025-11-05T15:27:43.572-05:00 Generated source
 * version: 4.0.8
 */
@WebServiceClient(
    name = "TylerCourtRecordMDEService",
    wsdlLocation = "file:../stage/illinois-ECF5-TylerCourtRecordMDEService.wsdl",
    targetNamespace = "urn:tyler:ecf:v5.0:extensions:TylerCourtRecordMDE")
public class TylerCourtRecordMDEService extends Service {

  public static final URL WSDL_LOCATION;

  public static final QName SERVICE =
      new QName("urn:tyler:ecf:v5.0:extensions:TylerCourtRecordMDE", "TylerCourtRecordMDEService");
  public static final QName TylerCourtRecordMDE =
      new QName("urn:tyler:ecf:v5.0:extensions:TylerCourtRecordMDE", "TylerCourtRecordMDE");

  static {
    URL url = null;
    try {
      url = URI.create("file:../stage/illinois-ECF5-TylerCourtRecordMDEService.wsdl").toURL();
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(TylerCourtRecordMDEService.class.getName())
          .log(
              java.util.logging.Level.INFO,
              "Can not initialize the default wsdl from {0}",
              "file:../stage/illinois-ECF5-TylerCourtRecordMDEService.wsdl");
    }
    WSDL_LOCATION = url;
  }

  public TylerCourtRecordMDEService(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public TylerCourtRecordMDEService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public TylerCourtRecordMDEService() {
    super(WSDL_LOCATION, SERVICE);
  }

  public TylerCourtRecordMDEService(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }

  public TylerCourtRecordMDEService(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  public TylerCourtRecordMDEService(
      URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   * @return returns TylerCourtRecordMDE
   */
  @WebEndpoint(name = "TylerCourtRecordMDE")
  public ecf5.v2024_6.tyler.ecf.v5_0.extensions.tylercourtrecordmde.TylerCourtRecordMDE
      getTylerCourtRecordMDE() {
    return super.getPort(TylerCourtRecordMDE, TylerCourtRecordMDE.class);
  }

  /**
   * @param features A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.
   *     Supported features not in the <code>features</code> parameter will have their default
   *     values.
   * @return returns TylerCourtRecordMDE
   */
  @WebEndpoint(name = "TylerCourtRecordMDE")
  public TylerCourtRecordMDE getTylerCourtRecordMDE(WebServiceFeature... features) {
    return super.getPort(TylerCourtRecordMDE, TylerCourtRecordMDE.class, features);
  }
}
