
package ecfv5.https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wsdl.filingassemblymde;

//import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.5.0-SNAPSHOT-3e40a2387febaf00f47fe893d97ffdf63aaa4626
 * 2021-11-08T17:57:08.551-05:00
 * Generated source version: 3.5.0-SNAPSHOT
 *
 */

public class FilingAssemblyMDE_FilingAssemblyMDEPort_Server{

  /*
    protected FilingAssemblyMDE_FilingAssemblyMDEPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new FilingAssemblyMDEPortImpl();
        String address = "https://efile.suffolklitlab.org/filingassembly/callbacks/FilingAssemblyMDEPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new FilingAssemblyMDE_FilingAssemblyMDEPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
    */
}
