package ecf5;

import ecf5.v2024_6.tyler.ecf.v5_0.extensions.tylercourtschedulingmde.TylerCourtSchedulingMDE;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 4.0.8 2025-11-05T15:27:55.605-05:00 Generated source
 * version: 4.0.8
 */
@WebServiceClient(
    name = "TylerCourtSchedulingMDEService",
    wsdlLocation = "file:../stage/illinois-ECF5-TylerCourtSchedulingMDEService.wsdl",
    targetNamespace = "urn:tyler:ecf:v5.0:extensions:TylerCourtSchedulingMDE")
public class TylerCourtSchedulingMDEService extends Service {

  public static final URL WSDL_LOCATION;

  public static final QName SERVICE =
      new QName(
          "urn:tyler:ecf:v5.0:extensions:TylerCourtSchedulingMDE",
          "TylerCourtSchedulingMDEService");
  public static final QName TylerCourtSchedulingMDE =
      new QName("urn:tyler:ecf:v5.0:extensions:TylerCourtSchedulingMDE", "TylerCourtSchedulingMDE");

  static {
    URL url = null;
    try {
      url = URI.create("file:../stage/illinois-ECF5-TylerCourtSchedulingMDEService.wsdl").toURL();
    } catch (MalformedURLException e) {
      java.util.logging.Logger.getLogger(TylerCourtSchedulingMDEService.class.getName())
          .log(
              java.util.logging.Level.INFO,
              "Can not initialize the default wsdl from {0}",
              "file:../stage/illinois-ECF5-TylerCourtSchedulingMDEService.wsdl");
    }
    WSDL_LOCATION = url;
  }

  public TylerCourtSchedulingMDEService(URL wsdlLocation) {
    super(wsdlLocation, SERVICE);
  }

  public TylerCourtSchedulingMDEService(URL wsdlLocation, QName serviceName) {
    super(wsdlLocation, serviceName);
  }

  public TylerCourtSchedulingMDEService() {
    super(WSDL_LOCATION, SERVICE);
  }

  public TylerCourtSchedulingMDEService(WebServiceFeature... features) {
    super(WSDL_LOCATION, SERVICE, features);
  }

  public TylerCourtSchedulingMDEService(URL wsdlLocation, WebServiceFeature... features) {
    super(wsdlLocation, SERVICE, features);
  }

  public TylerCourtSchedulingMDEService(
      URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
    super(wsdlLocation, serviceName, features);
  }

  /**
   * @return returns TylerCourtSchedulingMDE
   */
  @WebEndpoint(name = "TylerCourtSchedulingMDE")
  public TylerCourtSchedulingMDE getTylerCourtSchedulingMDE() {
    return super.getPort(TylerCourtSchedulingMDE, TylerCourtSchedulingMDE.class);
  }

  /**
   * @param features A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.
   *     Supported features not in the <code>features</code> parameter will have their default
   *     values.
   * @return returns TylerCourtSchedulingMDE
   */
  @WebEndpoint(name = "TylerCourtSchedulingMDE")
  public TylerCourtSchedulingMDE getTylerCourtSchedulingMDE(WebServiceFeature... features) {
    return super.getPort(TylerCourtSchedulingMDE, TylerCourtSchedulingMDE.class, features);
  }
}
