package tyler.efm;

import java.net.URL;

import javax.xml.namespace.QName;

import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import tyler.efm.latest.services.IEfmFirmService;
import jakarta.xml.ws.Service;

/**
 * This class was originally generated by Apache CXF 4.0.8
 * 2025-06-13T15:28:22.368-04:00
 * Generated source version: 4.0.8
 *
 */
@WebServiceClient(name = "EfmFirmService",
                  targetNamespace = "urn:tyler:efm:services")
public class EfmFirmService extends Service {

    public static final QName SERVICE = new QName("urn:tyler:efm:services", "EfmFirmService");
    public static final QName BasicHttpBindingIEfmFirmService = new QName("urn:tyler:efm:services", "BasicHttpBinding_IEfmFirmService");

    public EfmFirmService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    /**
     *
     * @return
     *     returns IEfmFirmService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEfmFirmService")
    public IEfmFirmService getBasicHttpBindingIEfmFirmService() {
        return super.getPort(BasicHttpBindingIEfmFirmService, IEfmFirmService.class);
    }

    @WebEndpoint(name = "BasicHttpBinding_IEfmFirmService")
    public tyler.efm.v2022_1.services.IEfmFirmService getBasicHttpBindingV2022IEfmFirmService() {
        return super.getPort(BasicHttpBindingIEfmFirmService, tyler.efm.v2022_1.services.IEfmFirmService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEfmFirmService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEfmFirmService")
    public IEfmFirmService getBasicHttpBindingIEfmFirmService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIEfmFirmService, IEfmFirmService.class, features);
    }

}
