
package oasis.names.tc.legalxml_courtfiling.wsdl.webservicesprofile_definitions_4_0;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import tyler.efm.wsdl.webservicesprofile_implementation_4_0.ServiceMDEService;

/**
 * This class was generated by Apache CXF 3.5.0-SNAPSHOT-3e40a2387febaf00f47fe893d97ffdf63aaa4626
 * 2021-07-21T17:06:29.291-04:00
 * Generated source version: 3.5.0-SNAPSHOT
 *
 */
public final class ServiceMDEPort_ServiceMDEPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:tyler:efm:wsdl:WebServicesProfile-Implementation-4.0", "ServiceMDEService");

    private ServiceMDEPort_ServiceMDEPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = null; //ServiceMDEService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ServiceMDEService ss = new ServiceMDEService(wsdlURL, SERVICE_NAME);
        ServiceMDEPort port = ss.getServiceMDEPort();

        {
        System.out.println("Invoking serveFiling...");
        oasis.names.tc.legalxml_courtfiling.schema.xsd.corefilingmessage_4.CoreFilingMessageType _serveFiling_coreFilingMessage = null;
        oasis.names.tc.legalxml_courtfiling.schema.xsd.servicereceiptmessage_4.ServiceReceiptMessageType _serveFiling__return = port.serveFiling(_serveFiling_coreFilingMessage);
        System.out.println("serveFiling.result=" + _serveFiling__return);


        }

        System.exit(0);
    }

}
