<?xml version="1.0" encoding="UTF-8" standalone="no"?><definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:tyler:ecf:v5.0:extensions:TylerCourtSchedulingMDE" xmlns:wrappers="urn:tyler:ecf:v5.0:extensions:wrappers" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsrmp="http://docs.oasis-open.org/ws-rx/wsrmp/200702" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:tyler:ecf:v5.0:extensions:TylerCourtSchedulingMDE">
	<wsp:UsingPolicy wsdl:required="true"/>
	<wsp:Policy wsu:Id="MyPolicy">
		<wsrmp:RMAssertion/>
	</wsp:Policy>
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="urn:tyler:ecf:v5.0:extensions:wrappers" schemaLocation="../base/ecfv5-602d09642dfaa9bc.xsd"/>
		</xsd:schema>
	</wsdl:types>
	
	<!-- messages -->
	<message name="GetReturnDateRequest">
		<part element="wrappers:GetReturnDateRequest" name="body"/>
	</message>
	<message name="GetReturnDateResponse">
		<part element="wrappers:GetReturnDateResponse" name="body"/>
	</message>
		
	<!-- ports -->
	<portType name="TylerCourtSchedulingMDE">
		<operation name="GetReturnDate">
			<input message="tns:GetReturnDateRequest"/>
			<output message="tns:GetReturnDateResponse"/>
		</operation>
	</portType>
	
	<!-- bindings s -->
	<binding name="TylerCourtSchedulingMDESoap" type="tns:TylerCourtSchedulingMDE">
		<wsp:PolicyReference URI="#MyPolicy"/>
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="GetReturnDate">
			<!-- An operation to retrieve a return date -->
			<soap:operation soapAction="urn:tyler:ecf:v5.0:extensions:TylerCourtSchedulingMDE/GetReturnDate"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
</definitions>