package ecf4.latest.tyler.efm.wsdl.webservicesprofile_implementation_4_0;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;
import ecf4.latest.oasis.names.tc.legalxml_courtfiling.wsdl.webservicesprofile_definitions_4_0.FilingAssemblyMDEPort;

/**
 * This class was generated by Apache CXF 4.0.8
 * 2026-01-27T15:46:06.074-05:00
 * Generated source version: 4.0.8
 *
 */
@WebServiceClient(name = "FilingAssemblyMDEService",
                  wsdlLocation = "file:/Users/bwilley/Developer/EfileProxyServer/scripts/../TylerEcf4/src/main/resources/wsdl/v2025_4/stage/illinois-ECF-4.0-FilingAssemblyMDEService.wsdl",
                  targetNamespace = "urn:tyler:efm:wsdl:WebServicesProfile-Implementation-4.0")
public class FilingAssemblyMDEService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("urn:tyler:efm:wsdl:WebServicesProfile-Implementation-4.0", "FilingAssemblyMDEService");
    public static final QName FilingAssemblyMDEPort = new QName("urn:tyler:efm:wsdl:WebServicesProfile-Implementation-4.0", "FilingAssemblyMDEPort");
    static {
        URL url = null;
        try {
            url = URI.create("file:/Users/bwilley/Developer/EfileProxyServer/scripts/../TylerEcf4/src/main/resources/wsdl/v2025_4/stage/illinois-ECF-4.0-FilingAssemblyMDEService.wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FilingAssemblyMDEService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/bwilley/Developer/EfileProxyServer/scripts/../TylerEcf4/src/main/resources/wsdl/v2025_4/stage/illinois-ECF-4.0-FilingAssemblyMDEService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FilingAssemblyMDEService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FilingAssemblyMDEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FilingAssemblyMDEService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public FilingAssemblyMDEService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public FilingAssemblyMDEService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public FilingAssemblyMDEService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns FilingAssemblyMDEPort
     */
    @WebEndpoint(name = "FilingAssemblyMDEPort")
    public FilingAssemblyMDEPort getFilingAssemblyMDEPort() {
        return super.getPort(FilingAssemblyMDEPort, FilingAssemblyMDEPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FilingAssemblyMDEPort
     */
    @WebEndpoint(name = "FilingAssemblyMDEPort")
    public FilingAssemblyMDEPort getFilingAssemblyMDEPort(WebServiceFeature... features) {
        return super.getPort(FilingAssemblyMDEPort, FilingAssemblyMDEPort.class, features);
    }

}
