name: JavaCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode -Preproducible verify javadoc:javadoc

  dockerimage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build whole Dockerfile
        run: docker build --target release --tag test-efspjava-image .
