# Example fly.yml
# You can use this as a template for the Fly.io continuous deployment GitHub workflow config file.
# Copy into .github/workflows/fly.yml for GitHub to see this file.
# For more details, check out:
# https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/
name: Fly Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --build-arg CI_COMMIT_SHA=`git rev-parse HEAD`
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
