package ecfv5.https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wsdl.courtschedulingmde;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0-SNAPSHOT-3e40a2387febaf00f47fe893d97ffdf63aaa4626
 * 2021-09-15T00:22:19.769-04:00
 * Generated source version: 3.5.0-SNAPSHOT
 *
 */
@WebServiceClient(name = "CourtSchedulingMDE",
                  wsdlLocation = "file:EfileProxyServer/src/main/resources/wsdl/v5/CourtSchedulingMDE.wsdl",
                  targetNamespace = "https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/WSDL/CourtSchedulingMDE")
public class CourtSchedulingMDE_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/WSDL/CourtSchedulingMDE", "CourtSchedulingMDE");
    public final static QName CourtSchedulingMDEPort = new QName("https://docs.oasis-open.org/legalxml-courtfiling/ns/v5.0/WSDL/CourtSchedulingMDE", "CourtSchedulingMDEPort");
    static {
        URL url = CourtSchedulingMDE_Service.class.getClassLoader().getResource("wsdl/v5/CourtSchedulingMDE.wsdl");;
        if (url == null) {
          org.slf4j.LoggerFactory.getLogger(CourtSchedulingMDE_Service.class.getName()).info(
               "Can not initialize the default wsdl from {0}", "classpath:wsdl/v5/CourtSchedulingMDE.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CourtSchedulingMDE_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CourtSchedulingMDE_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourtSchedulingMDE_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CourtSchedulingMDE_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CourtSchedulingMDE_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CourtSchedulingMDE_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CourtSchedulingMDE
     */
    @WebEndpoint(name = "CourtSchedulingMDEPort")
    public CourtSchedulingMDE getCourtSchedulingMDEPort() {
        return super.getPort(CourtSchedulingMDEPort, CourtSchedulingMDE.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourtSchedulingMDE
     */
    @WebEndpoint(name = "CourtSchedulingMDEPort")
    public CourtSchedulingMDE getCourtSchedulingMDEPort(WebServiceFeature... features) {
        return super.getPort(CourtSchedulingMDEPort, CourtSchedulingMDE.class, features);
    }

}
