
package ecfv5.https.docs_oasis_open_org.legalxml_courtfiling.ns.v5_0.wsdl.courtschedulingmde;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.5.0-SNAPSHOT-3e40a2387febaf00f47fe893d97ffdf63aaa4626
 * 2021-09-10T12:30:55.353-04:00
 * Generated source version: 3.5.0-SNAPSHOT
 *
 * NOTE(brycew): DON'T use this. It's autogenerated, and kinda dumb.
 */

public class CourtSchedulingMDE_CourtSchedulingMDEPort_Server{

    protected CourtSchedulingMDE_CourtSchedulingMDEPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new Object(); //new CourtSchedulingMDEPortImpl();
        String address = "https://localhost/...";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new CourtSchedulingMDE_CourtSchedulingMDEPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
